name: flux_origin
description: A translation desktop application for Windows
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Window management
  window_manager: ^0.3.0
  
  # UI dependencies
  google_fonts: ^6.1.0
  font_awesome_flutter: ^10.6.0
  flutter_animate: ^4.3.0
  
  # State management
  provider: ^6.1.0
  file_picker: ^10.3.7
  shared_preferences: ^2.5.3
  http: ^1.1.0
  url_launcher: ^6.3.2
  csv: ^6.0.0
  html: ^0.15.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
