name: flux_origin
description: A translation desktop application for Windows
publish_to: 'none'
version: 1.1.0+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Window management
  window_manager: ^0.3.0
  
  # UI dependencies
  google_fonts: ^6.1.0
  font_awesome_flutter: ^10.6.0
  flutter_animate: ^4.3.0
  
  # State management
  provider: ^6.1.0
  file_picker: ^10.3.7
  shared_preferences: ^2.5.3
  http: ^1.1.0
  url_launcher: ^6.3.2
  csv: ^6.0.0
  html: ^0.15.4
  desktop_drop: ^0.4.4
  
  # File parsing
  epubx: ^4.0.0
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true

# ... (giữ nguyên phần trên của file pubspec.yaml)

msix_config:
  display_name: FluxOrigin
  publisher_display_name: d-init-d
  identity_name: d-init-d.FluxOrigin  # QUAN TRỌNG: Nếu đăng Store, phải lấy tên Identity từ Partner Center
  publisher: CN=94D446F9-8A96-471F-9749-DFF18CBA6CD8     # QUAN TRỌNG: Nếu đăng Store, phải lấy chuỗi Publisher ID (ví dụ: CN=92837...) từ Partner Center
  msix_version: 1.0.0.0
  logo_path: windows/runner/resources/app_icon.ico
  capabilities: "internetClient, internetClientServer"
  # Các quyền truy cập file nếu app cần (vì MSIX chạy trong sandbox)
  # un-comment nếu app cần đọc/ghi file tự do ngoài thư mục app
  # execution_alias: fluxorigin

